Add a condition to add rt library with Linux and not with APPLE
- Need to link rt library otherwise we have some 'undefined reference to
`shm_unlink''