Test both CDSP0, CDSP1 for Makena
Previously, we would encounter occasional failures that looked like the
log below.  This was caused by the test expecting 'DSP Image Creation Date'
text to hold back the launch of the CDSP0 test with "fastrpc_calc_test", but
this message is printed when each CDSP0 and CDSP1 boots.

To address this bug and add more coverage, we'll just wait for both DSPs
to boot and then test both.

    MEM_MAPPING_PHYS_CONTIGUOUS: cannot allocate region with requested phys_addr=1678f000
    XXX_SM: smem_alloc: SMEM allocation success. smem_type=633, buf_size=256 and offset = 0x?.Successfully registered CVP driver with QDI!
    pd_mon_mdf: Protection Domain Launched mdf_process
    ERROR: PROCESS SPAWN FAILED: mdf_process
    **********************************
    * DSP Image Creation Date: ENGG time:Q6_BUILD_TS_Tue_Sep_27_10:44:58_PST_2022_makena.cdsp1.prodQ
    *******************************************************
    # fastrpc_calc_test 0 100 3
    fastrpc_calc_test 0 100 3
    - starting calculator test
    - creating sequence of numbers from 0 to 99
    glink channel state: up
    glink_open event handler start
    glink_open event handler done
    XXX_SM: smem_alloc: SMEM allocation success. smem_type=601, buf_size=256 and offset = 0x?.Successfully registered CVP driver with QDI!
    pd_mon_mdf: Protection Domain Launched mdf_process
    ERROR: PROCESS SPAWN FAILED: mdf_process
    **********************************
    * DSP Image Creation Date: ENGG time:Q6_BUILD_TS_Wed_Sep_28_10:49:09_PST_2022_makena.cdsp0.prodQ
    *******************************************************
    Starting platform with ENV {'QQVP_IMAGE_DIR': '/builds/qqvp/quic-vp/firmware-images/makena/default', 'PWD': '/builds/qqvp/quic-vp/build'}
    Traceback (most recent call last):
      File "/builds/qqvp/quic-vp/tests/Interaction_test.py", line 68, in <module>
        AssertThat(fastrpc_calc_test()).IsTrue()
      File "/builds/qqvp/quic-vp/tests/Interaction_test.py", line 61, in fastrpc_calc_test
        child.expect('- sum = 4950')
      File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 343, in expect
        return self.expect_list(compiled_pattern_list,
      File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 372, in expect_list
        return exp.expect_loop(timeout)
      File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 181, in expect_loop
        return self.timeout(e)
      File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 144, in timeout
        raise exc
    pexpect.exceptions.TIMEOUT: Timeout exceeded.
    <pexpect.pty_spawn.spawn object at 0x7fad26cd0b20>

Signed-off-by: Brian Cain <bcain@quicinc.com>